services:
  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=api

  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        SERVICE: api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "db"

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    environment:
      - API_URL=/docs/swagger.yaml
    volumes:
      - "./api:/usr/share/nginx/html/docs"

